"""migrate conversation to dashboard

Revision ID: c144c6d09e3c
Revises: 008_conversations
Create Date: 2026-08-08 13:39:22.109954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c144c6d09e3c'
down_revision: Union[str, None] = '008_conversations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM chat_messages")
    op.execute("DELETE FROM conversations")
    op.add_column('conversations', sa.Column('dashboard_id', sa.String(), nullable=False))
    op.drop_index('ix_conversations_dataset_id', table_name='conversations')
    op.drop_constraint('uq_conversation_user_dataset', 'conversations', type_='unique')
    op.create_index(op.f('ix_conversations_dashboard_id'), 'conversations', ['dashboard_id'], unique=False)
    op.create_unique_constraint('uq_conversation_user_dashboard', 'conversations', ['user_id', 'dashboard_id'])
    op.create_foreign_key(None, 'conversations', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversations', 'dataset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM chat_messages")
    op.execute("DELETE FROM conversations")
    op.add_column('conversations', sa.Column('dataset_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint('uq_conversation_user_dashboard', 'conversations', type_='unique')
    op.drop_index(op.f('ix_conversations_dashboard_id'), table_name='conversations')
    op.create_unique_constraint(op.f('uq_conversation_user_dataset'), 'conversations', ['user_id', 'dataset_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_conversations_dataset_id'), 'conversations', ['dataset_id'], unique=False)
    op.drop_column('conversations', 'dashboard_id')
    # ### end Alembic commands ###
