"""add is_public to dashboard

Revision ID: dcf251097739
Revises: 003_dataset_blobs
Create Date: 2026-07-29 11:00:19.082783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf251097739'
down_revision: Union[str, None] = '003_dataset_blobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'is_public')
    # ### end Alembic commands ###
